# Generated by Django 5.1.5 on 2025-03-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('goal', models.IntegerField()),
                ('type', models.BooleanField(default=True)),
            ],
        ),
    ]
