# Generated by Django 5.1.5 on 2025-03-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenges_completed',
            field=models.IntegerField(default=0),
        ),
    ]
