# Generated by Django 5.1.5 on 2025-03-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
