# Generated by Django 5.1.5 on 2025-03-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
